# Author: Xuelin Wei
# Email: xuelinwei@seu.edu.cn
# Date: 2024-03-21 15:37:34
# LastEditTime: 2024-03-21 15:53:33
# LastEditors: xuelinwei xuelinwei@seu.edu.cn
# FilePath: /FreqDefense/scripts/train.py

resume: True
random_seed: 981217
resume_result: 'trn3-224/test'
train_config:
  distributed: False
  lr: 2.0e-5
  # the lr is slightly larger
  lr_decay_step: 200
  lr_decay_rate: 5.0e-1
  epochs: 400
  print_freq: 4
  masked:
    enable: True
    method: 'randomall'
    size: 60
  blend:
    enable: False
  f_distortion:
    enable: True
    add_self: False
    f_alpha: 0.1
    f_beta: 1
    f_scale: 500
  feature_loss:
    - 'placeholder'
    # - 'l1'
    # - 'ffl'
  img_loss:
    - 'l1'
    - 'lpips'
    - 'ffl'
  img_loss_weight: 1.0
  ffl_weight: 1.0