# Author: Xuelin Wei
# Email: xuelinwei@seu.edu.cn
# Date: 2024-03-21 15:37:34
# LastEditTime: 2024-03-21 15:53:33
# LastEditors: xuelinwei xuelinwei@seu.edu.cn
# FilePath: /FreqDefense/scripts/train.py

resume: False
random_seed: 981217
result_name: 'trn3/test'
data_config:
  dataset_name: 'cifar10'
  data_root: './data/'
  batch_size: 32
  num_workers: 8
model_config:
  model_name: 'resnet18'
  gaussian_layer: True
  gaussian_group_size: 5
train_config:
  distributed: False
  lr: 2.0e-4
  # the lr is slightly larger
  lr_decay_step: 1000
  lr_decay_rate: 5.0e-1
  epochs: 100
  print_freq: 4
  masked:
    enable: True
    method: 'randomall'
    size: 10
  blend:
    enable: False
  f_distortion:
    enable: True
    add_self: False
    f_alpha: 0.2
    f_beta: 1
    f_scale: 10
  feature_loss:
    - 'placeholder'
    # - 'l1'
    # - 'ffl'
  img_loss:
    - 'l1'
    - 'lpips'
    - 'ffl'
  img_loss_weight: 2.0
  ffl_weight: 1.0