# Author: Xuelin Wei
# Email: xuelinwei@seu.edu.cn
# Date: 2024-03-21 15:37:34
# LastEditTime: 2024-03-21 15:53:33
# LastEditors: xuelinwei xuelinwei@seu.edu.cn
# FilePath: /FreqDefense/scripts/train.py

resume: False
random_seed: 981217
# result_name: 'test2'
data_config:
  dataset_name: '20-imagenet'
  data_root: './data/'
  batch_size: 32
  num_workers: 4
model_config:
  bs_chanel: 64
  dropout: 0.2
  d_factor: 6
train_config:
  distributed: False
  lr: 2.0e-4
  lr_decay_step: 200
  lr_decay_rate: 4.0e-1
  epochs: 800
  print_freq: 4
  f_distortion: True
  f_alpha: 0.1
  f_beta: 1