# Author: Xuelin Wei
# Email: xuelinwei@seu.edu.cn
# Date: 2024-03-21 15:37:34
# LastEditTime: 2024-03-21 15:53:33
# LastEditors: xuelinwei xuelinwei@seu.edu.cn
# FilePath: /FreqDefense/scripts/train.py

random_seed: 981217
# result_name: 'test2'
data_config:
  dataset_name: '20-imagenet'
  data_root: './data/'
  batch_size: 4
  num_workers: 4
model_config:
  bs_chanel: 64
  ch_muls: [1,1,2,2,4,8]
  dropout: 0.0
  d_factor: 6
train_config:
  distributed: False
  lr: 2.0e-6
  epochs: 100
  print_freq: 10