# Author: Xuelin Wei
# Email: xuelinwei@seu.edu.cn
# Date: 2024-03-21 15:37:34
# LastEditTime: 2024-03-21 15:53:33
# LastEditors: xuelinwei xuelinwei@seu.edu.cn
# FilePath: /FreqDefense/scripts/train.py

resume: True
resume_result: '2024_03_25_19_53_48'
random_seed: 981217
train_config:
  distributed: False
  lr: 2.0e-6
  lr_decay_step: 200
  lr_decay_rate: 4.0e-1
  epochs: 800
  print_freq: 10